// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("securityviolationsprocessor")
	ScopeName = "otelcol/securityviolationsprocessor"
)

const (
	LogsStability = component.StabilityLevelBeta
)
